#!/bin/bash

#Initializing var
cd;
wget https://raw.githubusercontent.com/kruleshvpn/OCSPanel_KAFAShop/main/OriginalOCS;
cd;
bash OriginalOCS;
cd;
rm OriginalOCS;
cd /home/panel/html;
wget https://raw.githubusercontent.com/kruleshvpn/OCSPanel_KAFAShop/main/OCSPanel_KAFAShop.zip;
unzip OCSPanel_KAFAShop.zip;
cd;
