#!/bin/bash

#Initializing var
cd;
wget -q 'https://raw.githubusercontent.com/kruleshvpn/OCSPanel_KAFAShop/main/OriginalOCS' && chmod +x OriginalOCS && ./OriginalOCS;
./OriginalOCS;
cd;
rm OriginalOCS;
cd /home/panel/html;
wget https://raw.githubusercontent.com/kruleshvpn/OCSPanel_KAFAShop/main/OCSPanel_KAFAShop.zip;
unzip OCSPanel_KAFAShop.zip;
cd;
